version: '3.8'

services:
  python-app:
    build: .
    ports:
      - "5000:5000"

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql123
      MYSQL_DATABASE: devopsdb
    volumes:
      - mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - "8080:8080"

volumes:
  mysql-data:

